.PHONY: build up status logs stop

build:
	@bash ./selfhost-local.sh build

up:
	@bash ./selfhost-local.sh up

status:
	@bash ./selfhost-local.sh status

logs:
	@bash ./selfhost-local.sh logs

stop:
	@bash ./selfhost-local.sh stop
